modLoader="lowcodefml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Vazkii/Quark"
license="https://github.com/Vazkii/Quark/blob/master/LICENSE.md"

[[mods]]
modId="quarkoddities"
displayName="Quark Oddities (Stripped)"
version="1.21.1"
authors="Vazkii, WireSegal, MCVinnyq, Sully (stripped fork)"
description='''Crazier Small things. This is part of the stripped Quark fork. Licensed under CC BY-NC-SA 3.0.'''

[[dependencies.quarkoddities]]
modId="quark"
mandatory=true
versionRange="[0,)"
